#!/bin/sh
# postinst script for middleman
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
    configure)
	    . /usr/share/debconf/confmodule

	    if ! (getent group middleman) > /dev/null 2>&1; then
	        addgroup --quiet --system middleman > /dev/null
		fi

		if ! (getent passwd middleman) > /dev/null 2>&1; then
		    adduser --quiet --system --home /var/lib/middleman --ingroup middleman --no-create-home --shell /bin/false middleman
		fi

		chmod 0755 /etc/init.d/middleman

		if [ ! -d /var/log/middleman ]; then
            mkdir /var/log/middleman
            chown -R middleman:adm /var/log/middleman/
            chmod 0755 /var/log/middleman/
        fi

        if [ ! -d /var/lib/middleman ]; then
            mkdir /var/lib/middleman
            chown middleman:middleman -R /var/lib/middleman/ /etc/middleman
            chmod -R 0755 /etc/middleman/
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
