#!/bin/sh
# postrm script for middleman
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <overwriter>
#          <overwriter-version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


case "$1" in
	purge)
        echo "Purging middleman..." >&2
        if (getent passwd middleman) > /dev/null 2>&1; then
            userdel middleman || true
        fi

        if (getent group middleman) > /dev/null 2>&1; then
            groupdel middleman || true
        fi

        [ -e /var/lib/middleman ] && rm -rf /var/lib/middleman
        [ -e /var/log/middleman ] && rm -rf /var/log/middleman
        [ -e /usr/share/middleman ] && rm -rf /usr/share/middleman
        [ -e /etc/middleman ] && rm -rf /etc/middleman
	;;

    upgrade|failed-upgrade|abort-upgrade)
        echo "upgrade ignored"
    ;;

    remove|abort-install|disappear)
        [ -e /usr/share/middleman ] && rm -rf /usr/share/middleman
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
